---
name: Merge to main
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run test && npm run build
      - run: echo "REACT_APP_VERSION=$(git describe --always --dirty)" >> $GITHUB_ENV
      - run: echo "${{ env.REACT_APP_VERSION }}"
      - uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          sourcemaps: "./build"
          environment: "production"
          version: ${{ env.REACT_APP_VERSION }}
